### ISSUE TITLE
Behavioral differences with Chrome's implementation of trusted signals fetching

### ISSUE THREAD

**Issue by taymonbeal** [google/fledge-shim#69]
Looking through https://source.chromium.org/chromium/chromium/src/+/main:content/services/auction_worklet/trusted_bidding_signals.cc, there are two apparent differences with how we fetch trusted signals:

1. FLEDGE Shim appends the `hostname` and `keys` parameters after any existing query parameters in the provided URL. Chrome appears to require that the provided URL have no query parameters.
2. FLEDGE Shim escapes each key, joins them with `,`, then escapes them again. Chrome appears to do only one layer of escaping, which means that `keys` may be ambiguous if there's a `,` in one of them.

We should find out whether these are bugs in Chrome's implementation or whether the intent is for the feature to be specified this way.

**Comment by MattMenke2** [comment]
Both of these look to be incorrect.

1.  We disallow query parameters on input URLs instead of appending them, since if there's an existing keys=, or KeYs= field, it's ambiguous what we should do.  The linked code actually replaces all query params, but earlier in the stack we disallow query params (or at least that was the plan - it's possible I broke that a day or two when refactoring things.  Need to add a test for it)

2. Looks to be incorrect - there is no second escape.  GURL doesn't escape commas, net::EscapeQueryParamValue() does, and net::EscapeQueryParamValue() is only called on keys, on the characters joining them.
